#!/usr/bin/env python
# Date Formats
y = "2015"
print ("""


╔╦╗╔═╗╔╦╗╔═╗╔═╗
 ║║╠═╣ ║ ║╣ ╚═╗
═╩╝╩ ╩ ╩ ╚═╝╚═╝

      Enter a month and day and see if
    that day is in the given month's range.

""")
from datetime import datetime,date

def getM():
    m = int(input("Enter the month : "))
    checkM(m)
    return m

def getD():
    d = int(input("Enter the day: "))
    checkD(d)
    return d



def checkM(month):
    mOk = "0"
    while mOk == "0":
        if int(month) <= 12 and int(month) > 0:
            mOk = "1"
            m = int(month)
            print(month)
            return(month)
            
            break
        else:
            getM()
            break


def checkD(day):
    dOk = "0"
    while dOk == "0":
       
        if int(day) <= 31 and int(day) > 0:
            dOk = "1"
            d = int(day)
            print(day)
            return (day)
            break
        else:
            getD()
            break


def validYN():
    m = getM()
    d = getD()
    stuff = "0"
    while stuff == "0":
        try:
            a = (datetime(2015,(m),(d)))
            print ("It checks out ! \nYour Date String: \n>> %s" % a)
            stuff = "1"
            pass
        except ValueError as e:
            print(e)
            main()
            break
def main():
    validYN()

main()

